data_all <- read.csv("DataAll_2.csv")
data_all[, 'Date'] <- as.Date(data_all[, 'Date'])
mygraph = ggplot(data_all, aes(Date,Age..Years.))
mygraph + geom_point(aes(fill=Sex, color=Sex, shape=Region), size=3) + theme_minimal() + theme(text = element_text(size=15)) +theme(axis.text.x = element_text(angle=90, hjust=1))+ scale_x_date(date_breaks="1 month") + labs(x="Month", y="Age (Years)")
ggsave("SupFig1.png")
